---
- name: Manage Equinix Metal device ports and VLANs
  hosts: localhost
  vars_files:
    - vars/equinix_metal_vars.yml
  tasks:
    - name: Get all devices in the project
      uri:
        url: "https://api.equinix.com/metal/v1/projects/{{ equinix_metal_project_id }}/devices"
        method: GET
        headers:
          Content-Type: "application/json"
          X-Auth-Token: "{{ equinix_metal_api_token }}"
        return_content: yes
      register: devices_info

    - name: Filter master* devices
      set_fact:
        master_devices: "{{ devices_info.json.devices | selectattr('hostname', 'match', '^master.*$') | list }}"

    - name: Extract eth0 MAC addresses from master* devices
      set_fact:
        eth0_macs: >-
          {{
            master_devices | 
            map(attribute='network_ports') | 
            map('selectattr', 'name', 'equalto', 'eth0') | 
            map('first') | 
            map(attribute='data') | 
            map(attribute='mac') | 
            list
          }}

    - name: Debug eth0 MAC addresses
      debug:
        msg: |
          {% for mac in eth0_macs %}
          Device {{ loop.index }} - eth0 MAC Address: {{ mac }}
          {% endfor %}

    - name: Extract bond0 port IDs from master* devices
      set_fact:
        bond0_ports: "{{ master_devices | map(attribute='network_ports') | map('selectattr', 'name', 'equalto', 'bond0') | map('first') | map(attribute='id') | list }}"

