---
- name: Manage Equinix Metal device ports and VLANs
  hosts: localhost
  vars_files:
    - vars/equinix_metal_vars.yml
  tasks:
    - name: Get all devices in the project
      uri:
        url: "https://api.equinix.com/metal/v1/projects/{{ equinix_metal_project_id }}/devices"
        method: GET
        headers:
          Content-Type: "application/json"
          X-Auth-Token: "{{ equinix_metal_api_token }}"
        return_content: yes
      register: devices_info

    - name: Filter master* devices
      set_fact:
        master_devices: "{{ devices_info.json.devices | selectattr('hostname', 'match', '^master.*$') | list }}"

    - name: Debug master_devices
      debug:
        var: master_devices

    - name: Extract bond0 port IDs from master* devices
      set_fact:
        bond0_ports: "{{ master_devices | map(attribute='network_ports') | map('selectattr', 'name', 'equalto', 'bond0') | map('first') | map(attribute='id') | list }}"

    - name: Convert bond0 NetworkBondPort into layer2 unbounded for each master device
      uri:
        url: "https://api.equinix.com/metal/v1/ports/{{ item }}/disbond"
        method: POST
        headers:
          Content-Type: "application/json"
          X-Auth-Token: "{{ equinix_metal_api_token }}"
        body_format: json
        body:
          bulk_disable: false
      loop: "{{ bond0_ports }}"
      register: disbond_result
      failed_when: disbond_result.status not in [200, 201, 202]

    - name: Debug disbond results
      debug:
        var: disbond_result

    - name: Get a list of all VLANs in the project
      uri:
        url: "https://api.equinix.com/metal/v1/projects/{{ equinix_metal_project_id }}/virtual-networks"
        method: GET
        headers:
          Content-Type: "application/json"
          X-Auth-Token: "{{ equinix_metal_api_token }}"
        return_content: yes
      register: vlan_list

    - name: Debug VLAN list
      debug:
        var: vlan_list

    - name: Get eth0 port IDs from master* devices
      set_fact:
        eth0_ports: "{{ master_devices | map(attribute='network_ports') | map('selectattr', 'name', 'equalto', 'eth0') | map('first') | map(attribute='id') | list }}"

    - name: Debug eth0_ports
      debug:
        var: eth0_ports

    - name: Assign VLANs to eth0 ports
      uri:
        url: "https://api.equinix.com/metal/v1/ports/{{ item }}/vlan-assignments/batches"
        method: POST
        headers:
          Content-Type: "application/json"
          X-Auth-Token: "{{ equinix_metal_api_token }}"
        body_format: json
        body:
          vlan_assignments: "{{ vlan_assignments }}"
      loop: "{{ eth0_ports }}"
      register: vlan_assignment_result
      failed_when: vlan_assignment_result.status not in [200, 201, 202]

    - name: Debug VLAN assignment results
      debug:
        var: vlan_assignment_result
